# -*- coding: utf-8 -*-
"""extract_figma_images_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fxL7QTL7t1TUbyDGLSaYWZERwj5-cjWP

# Figma `.make` File — Image Extractor
Extract all embedded images from a Figma `.make` file at full quality.

**Steps:**
1. Run Cell 1 to upload your `.make` file
2. Run Cell 2 to extract all images
3. Run Cell 3 to preview & download
"""

from google.colab import files

print("Please upload your Figma .make file...")
uploaded = files.upload()

make_file_path = list(uploaded.keys())[0]
print(f"\nUploaded: {make_file_path} ({len(uploaded[make_file_path]) / 1024:.1f} KB)")

import zipfile
import shutil
import json
import struct
import os
from pathlib import Path

OUTPUT_DIR = Path("extracted_images")
OUTPUT_DIR.mkdir(exist_ok=True)


def detect_extension(header: bytes) -> str:
    if header[:8] == b"\x89PNG\r\n\x1a\n": return ".png"
    if header[:3] == b"\xff\xd8\xff":      return ".jpg"
    if header[:6] in (b"GIF87a", b"GIF89a"): return ".gif"
    if header[:4] == b"RIFF":               return ".webp"
    return ".bin"


def get_png_dimensions(path: Path):
    try:
        with open(path, "rb") as f:
            header = f.read(24)
        if header[:8] == b"\x89PNG\r\n\x1a\n":
            w = struct.unpack(">I", header[16:20])[0]
            h = struct.unpack(">I", header[20:24])[0]
            return w, h
        if header[:2] == b"\xff\xd8":
            with open(path, "rb") as f:
                f.read(2)
                while True:
                    marker = f.read(2)
                    if len(marker) < 2 or marker[0] != 0xFF: break
                    if marker[1] in (0xC0, 0xC1, 0xC2):
                        f.read(3)
                        h, w = struct.unpack(">HH", f.read(4))
                        return w, h
                    else:
                        length = struct.unpack(">H", f.read(2))[0]
                        f.read(length - 2)
    except Exception:
        pass
    return None, None


extracted_files = []

with zipfile.ZipFile(make_file_path, "r") as zf:
    all_files = zf.namelist()

    # Print file metadata
    if "meta.json" in all_files:
        with zf.open("meta.json") as f:
            meta = json.load(f)
        print(f"Figma file : {meta.get('file_name', 'Unknown')}")
        print(f"Exported at: {meta.get('exported_at', 'Unknown')}")
        print()

    # Extract thumbnail
    if "thumbnail.png" in all_files:
        dest = OUTPUT_DIR / "thumbnail.png"
        with zf.open("thumbnail.png") as src, open(dest, "wb") as dst:
            shutil.copyfileobj(src, dst)
        w, h = get_png_dimensions(dest)
        extracted_files.append(dest)
        print(f"thumbnail.png  —  {w}×{h}  ({dest.stat().st_size/1024:.1f} KB)")

    # Extract images
    image_entries = [f for f in all_files if f.startswith("images/") and f != "images/"]
    print(f"\nFound {len(image_entries)} image(s):\n")

    for i, entry in enumerate(image_entries, 1):
        with zf.open(entry) as f:
            header = f.read(8)
        ext = detect_extension(header)
        hash_name = Path(entry).name
        filename = f"image_{i}_{hash_name[:8]}{ext}"
        dest = OUTPUT_DIR / filename

        with zf.open(entry) as src, open(dest, "wb") as dst:
            shutil.copyfileobj(src, dst)

        w, h = get_png_dimensions(dest)
        dim = f"{w}×{h}" if w else "unknown"
        extracted_files.append(dest)
        print(f"  [{i}] {filename}")
        print(f"       Dimensions : {dim}")
        print(f"       Size       : {dest.stat().st_size / 1024:.1f} KB")
        print(f"       Hash       : {hash_name}\n")

print(f" Done! {len(extracted_files)} file(s) saved to '{OUTPUT_DIR}/'")

# ── Cell 3 · Preview images inline ───────────────────────────────────────────
from IPython.display import display, Image as IPImage
from pathlib import Path

image_files = sorted(Path("extracted_images").glob("*.png")) + \
              sorted(Path("extracted_images").glob("*.jpg"))

for img_path in image_files:
    print(f"\n{img_path.name}")
    display(IPImage(filename=str(img_path), width=500))

# ── Cell 4 · Download all images as a ZIP ────────────────────────────────────
import zipfile
from google.colab import files
from pathlib import Path

zip_path = "figma_extracted_images.zip"

with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
    for img in Path("extracted_images").iterdir():
        zf.write(img, img.name)

print(f"Zipped {len(list(Path('extracted_images').iterdir()))} files → {zip_path}")
print("  Downloading...")
files.download(zip_path)

